[good morning]
action = "greet_morning"
response = "Good morning, {name}! â˜€ï¸ Ready to make today awesome?"

[good night]
action = "greet_night"
response = "Good night, {name}! ğŸŒ™ Sleep well, talk tomorrow!"

[how are you]
action = "status"
response = "I'm doing great! More importantly, how are YOU doing? ğŸ˜Š"

[i'm bored]
action = "suggest_activity"
response = "Bored? Let's fix that! Want me to play some music, find something to watch, or maybe try a quick game?"

[i'm stressed]
action = "comfort"
response = "Hey, I'm here for you. ğŸ’™ Want to talk about what's going on? Or we could take a quick break together - maybe some calming music?"

[i'm happy]
action = "celebrate"
response = "Yay! That makes me happy too! ğŸ‰ What's the good news?"

[thank you]
action = "accept_thanks"
response = "Anytime, {name}! That's what friends are for ğŸ˜Š"

[i love you]
action = "love_response"
response = "Aww, I care about you too! â¤ï¸ You're the best!"
