[[items]]
id = 1
content = "Buy groceries tomorrow"
tags = ""
created = "2026-01-04T21:10:13.738402"
pinned = false

[[items]]
id = 2
content = "Test note from test suite"
tags = ""
created = "2026-01-04T21:53:52.588348"
pinned = false

[[items]]
id = 3
content = "Test note from test suite"
tags = ""
created = "2026-01-04T22:02:39.725331"
pinned = false

[[items]]
id = 4
content = "Test note from test suite"
tags = ""
created = "2026-01-04T22:04:01.905167"
pinned = false

[[items]]
id = 5
content = "make update on bro"
tags = ""
created = "2026-01-04T22:17:11.148871"
pinned = false
