[[items]]
id = 1
message = "Call mom"
time = "2026-01-04T21:15:13.741521"
created = "2026-01-04T21:10:13.741521"
done = false

[[items]]
id = 2
message = "Test reminder"
time = "2026-01-04T22:53:52.588348"
created = "2026-01-04T21:53:52.588348"
done = false

[[items]]
id = 3
message = "Test reminder"
time = "2026-01-04T23:02:39.725331"
created = "2026-01-04T22:02:39.725331"
done = false

[[items]]
id = 4
message = "Test reminder"
time = "2026-01-04T23:04:01.906060"
created = "2026-01-04T22:04:01.906060"
done = false
