# Weather cache - Updated: 2026-01-04T22:17:15.236221

[bangalore]
location = "Bengaluru"
country = "India"
lat = 12.97194
lon = 77.59369
temp_c = 18.2
feels_like_c = 18.3
humidity = 71
wind_kmph = 6.2
wind_dir = "E"
condition = "Partly cloudy"
weather_code = 2
from_cache = False
cached_at = "2026-01-04T22:17:15.236221"