# Weather cache - Updated: 2026-01-04T22:13:54.339833

[bangalore]
location = "Bengaluru"
country = "India"
lat = 12.97194
lon = 77.59369
temp_c = 18.4
feels_like_c = 18.4
humidity = 70
wind_kmph = 6.2
wind_dir = "E"
condition = "Partly cloudy"
weather_code = 2
from_cache = False
cached_at = "2026-01-04T22:13:54.339833"