# Weather cache - Updated: 2026-01-04T22:04:31.910513

[london]
location = "London"
country = "United Kingdom"
lat = 51.50853
lon = -0.12574
temp_c = 1.3
feels_like_c = -2.4
humidity = 71
wind_kmph = 7.8
wind_dir = "WSW"
condition = "Mainly clear"
weather_code = 1
from_cache = False
cached_at = "2026-01-04T22:04:31.910513"